name = "Wasabi"
uuid = "cec542a4-22c5-46cb-8ca4-a46a7737b387"
authors = ["Mattia <iskyd@proton.me>"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
